extends: default

ignore: |
  _tmp/
  .bitrise.secrets.yml
  .git/
  .github/
  vendor/

rules:
  empty-lines: { max: 1 }
  line-length: disable
  document-start: disable
  indentation:
    indent-sequences: false
  comments-indentation: disable
  comments:
    level: error
  octal-values: enable
  quoted-strings:
    quote-type: double
    required: only-when-needed
  braces:
    min-spaces-inside: 1
    max-spaces-inside: 1
